/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javatprecetas;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javatprecetas.servicios.ServicioRecetas;
import javatprecetas.servicios.ServicioRecetasFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *Declaracion de la clase InterfazUsuario.
 * @author Grupo8
 */
public class InterfazUsuario extends javax.swing.JFrame {

    /**
     * Creacion de nueva forma InterfazUsuario
     */
    public InterfazUsuario() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pathRecetas = new javax.swing.JTextField();
        pathIngredientes = new javax.swing.JTextField();
        ButtonPathRecetas = new javax.swing.JButton();
        ButtonPathIngredientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ButtonAnalisisRecetas = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        ButtonAnalisisRecetas1 = new javax.swing.JButton();
        ButtonArchText = new javax.swing.JRadioButton();
        ButtonBBDD = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Analisis de recetas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Archivos de recetas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Archivo de ingredientes");

        pathRecetas.setEditable(false);
        pathRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathRecetasActionPerformed(evt);
            }
        });

        pathIngredientes.setEditable(false);
        pathIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathIngredientesActionPerformed(evt);
            }
        });

        ButtonPathRecetas.setText("Seleccionar");
        ButtonPathRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPathRecetasActionPerformed(evt);
            }
        });

        ButtonPathIngredientes.setText("Seleccionar");
        ButtonPathIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPathIngredientesActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ButtonAnalisisRecetas.setText("Analisis");
        ButtonAnalisisRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnalisisRecetasActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        ButtonAnalisisRecetas1.setText("Detalle");
        ButtonAnalisisRecetas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnalisisRecetas1ActionPerformed(evt);
            }
        });

        RadioButtonGroup.add(ButtonArchText);
        ButtonArchText.setSelected(true);
        ButtonArchText.setText("Archivos de Texto");
        ButtonArchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArchTextActionPerformed(evt);
            }
        });

        RadioButtonGroup.add(ButtonBBDD);
        ButtonBBDD.setText("Base de Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(ButtonPathRecetas)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(pathIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                                    .addComponent(pathRecetas)))
                                            .addComponent(ButtonPathIngredientes, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(38, 38, 38)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ButtonAnalisisRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ButtonAnalisisRecetas1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButtonArchText)
                                .addGap(122, 122, 122)
                                .addComponent(ButtonBBDD)
                                .addGap(206, 206, 206))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAnalisisRecetas)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAnalisisRecetas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonPathRecetas)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonPathIngredientes)
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonArchText)
                            .addComponent(ButtonBBDD))
                        .addGap(132, 132, 132))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pathIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathIngredientesActionPerformed

    private void pathRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathRecetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathRecetasActionPerformed

    private void ButtonAnalisisRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnalisisRecetasActionPerformed
      
        if((!pathIngredientes.getText().isEmpty()) && (!pathRecetas.getText().isEmpty())){
            OrganizadorRecetas cocina = new OrganizadorRecetas();
            try {
                this.jTextArea1.setText(cocina.arracarOrganizadorRecetas(this.pathRecetas.getText(),this.pathIngredientes.getText()));
            } catch (IOException ex) {
                Logger.getLogger(InterfazUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Completar la ruta de los path");
        }
      /*
      String tipo;
         if (ButtonArchText.isSelected()){
             tipo = "TXT";
            } else {
             tipo = "SQL";
         }
         
        ServicioRecetasFactory srFactory= new ServicioRecetasFactory();
        try {
            ServicioRecetas servicioRecetas = srFactory.obtenerServicio(tipo);
            //llamar al servicio recetas con el TXT
         // servicioRecetas.
        } catch (Exception ex) {
            Logger.getLogger(InterfazUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
         */
         
         /*
         String resultado="test";
         jTextArea1.setText("");
         jTextArea1.append(resultado);
        */
    }//GEN-LAST:event_ButtonAnalisisRecetasActionPerformed

    private void ButtonPathRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPathRecetasActionPerformed
        JFileChooser fileChooser = new JFileChooser(new File("."));
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int response = fileChooser.showOpenDialog(this);
        
        if(response == JFileChooser.APPROVE_OPTION){
                String ruta = "";
                try {
                    ruta = fileChooser.getSelectedFile().getCanonicalPath();
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                pathRecetas.setText(ruta);
                
        }
    }//GEN-LAST:event_ButtonPathRecetasActionPerformed

    private void ButtonPathIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPathIngredientesActionPerformed
        JFileChooser fileChooser = new JFileChooser(new File("."));
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int response = fileChooser.showOpenDialog(this);
        
        if(response == JFileChooser.APPROVE_OPTION){
                String ruta = "";
                try {
                    ruta = fileChooser.getSelectedFile().getCanonicalPath();
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                pathIngredientes.setText(ruta);
         }
    }//GEN-LAST:event_ButtonPathIngredientesActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonAnalisisRecetas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnalisisRecetas1ActionPerformed
        
        if((!pathIngredientes.getText().isEmpty()) && (!pathRecetas.getText().isEmpty())){
            OrganizadorRecetas cocina = new OrganizadorRecetas();
            try {
                this.jTextArea1.setText(cocina.arracarOrganizadorRecetasDetalle(this.pathRecetas.getText(),this.pathIngredientes.getText()));
            } catch (IOException ex) {
                Logger.getLogger(InterfazUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
           
         }else{
            JOptionPane.showMessageDialog(this,"Completar la ruta de los Archivos");
        }
        

    }//GEN-LAST:event_ButtonAnalisisRecetas1ActionPerformed

    private void ButtonArchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonArchTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnalisisRecetas;
    private javax.swing.JButton ButtonAnalisisRecetas1;
    private javax.swing.JRadioButton ButtonArchText;
    private javax.swing.JRadioButton ButtonBBDD;
    private javax.swing.JButton ButtonPathIngredientes;
    private javax.swing.JButton ButtonPathRecetas;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.ButtonGroup RadioButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pathIngredientes;
    private javax.swing.JTextField pathRecetas;
    // End of variables declaration//GEN-END:variables
}
